networks:
  todolist:
    driver: bridge

services:

  server_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports:
      - "5433:5432"
    networks:
      - todolist


  server:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
    depends_on:
      - server_db
    networks:
      - todolist

  client:
    build:
      context: ./Client/ToDoList_Client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - todolist