networks:
  todolist:
    driver: bridge

services:

  server_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ToDoList123@"
    ports:
      - "1433:1433"
    networks:
      - todolist

  server:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
    depends_on:
      - server_db
    networks:
      - todolist

  client:
    build:
      context: ./Client/ToDoList_Client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - todolist